[package]
name = "chip8_runtime"
version = "0.1.0"
edition = "2024"
default-run = "chip8_runtime"

[dependencies]
minifb = "0.28.0"
chip8_core = { path = "chip8_core" }

[workspace]
members = [
    ".",
    "chip8_core",
]
